#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'webserver-pkg==0.0.1','console_scripts','webserver_publisher_node'
__requires__ = 'webserver-pkg==0.0.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('webserver-pkg==0.0.1', 'console_scripts', 'webserver_publisher_node')()
    )
